Fix tests in Travis (#1013)
* gitignore

* Pin virtualenv = 20.0.35

Fix:

    Error: The requirement ('virtualenv>=20.0.35') is not allowed by
your [versions] constraint (20.0.26)
virtualenv = 20.0.35

See:

https://travis-ci.org/github/plone/plone.restapi/jobs/742090297#L251

* Pinn pep517 = 0.9.1

Fix:

    Error: The requirement ('pep517>=0.9') is not allowed by your
[versions] constraint (0.8.2)

See:

https://travis-ci.org/github/plone/plone.restapi/jobs/742090298#L250

* Use virtualenv in Travis tests

After the requirement virtualenv>=20.0.35, the version of virtualenv
installed in Python 2 of Travis  started to conflict with the version
required in the buildout.

Fix:

    ContextualVersionConflict: (virtualenv 16.1.0
(/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages),
Requirement.parse('virtualenv>=20.0.35'), set(['build']))

See:

https://travis-ci.org/github/plone/plone.restapi/jobs/742109179#L270

* Pinn importlib-metadata = 2.0.0

Fix:

    Error: The requirement ('importlib-metadata>=1') is not allowed by
your [versions] constraint (0.23)

See:

https://travis-ci.org/github/plone/plone.restapi/jobs/742116716